#! /usr/bin/env bash

set -x

kubectl auth can-i create pods
kubectl auth can-i create deployments
kubectl auth can-i create services
kubectl auth can-i create configmaps
kubectl auth can-i create secrets
kubectl auth can-i create pvc
kubectl auth can-i create certs

exec tail -f /dev/null
